<template>
  <div class="about">
    <h1>Hello!
      My name is Nick Bynum, and thank you for checking out my insulin dosing calculator.  In May of 2020, my life drastically changed, and in multiple ways.  Earlier in the year I had quit my job to persue my passion of become a software engineer.  After roughly a year of self teaching by watching and going through various css and html tutorials at the snails pace of a few hours a week, if I had that much time between family life and working my full time job; I decided to put it all on the line and quit my secure work, and started at a coding bootcamp to focus on my dream full time.  While I was finishing up bootcamp and working on my final project to pass the course and earn my certificate we noticed symptoms of diabetes with my 6 year old son.  He became constantly thirsty and always drinking water, and with that came more frequent bathroom trips which may have been expected but the red flag here was when he lost control of being able to make it to the bathroom in time in the middle of the night, bed wetting wasn’t really anything he’d ever experienced before even when potty-training we thought that maybe it was just a one-time thing but it happened a couple more times.  My wife expressed her concerns with my about the possibility of him being diabetic as we’re both somewhat familiar with it, my Mom being a Type 1, her Dad is Type 2, and we have a nephew that is Type 1 as well.
   She sent an email to his primary pediatrician, who told us to smell his breathe to see if it is sweet smelling.  My wife sent my son into my office to have me smell his breathe, it was in fact sweet smelling, so I agreed that we should get him set up with an appointment.  My wife called the pediatrician with the results of the sniff test, and they immediately made room for him to come in to be screened.  I was currently working on my final project and was 3 days into my 7 day project I was working on so I stayed home with the girls and continued on my project while my wife took my son to his appointment to get screened.  About 45 minutes to an hour after my wife left, my phone rings, and it’s her calling to let me know how the appointment went.  Immediately I could tell that she was holding back tears, she didn’t even have to say a word, but I already knew the screening didn’t look good.  It turns out his blood sugar was 398 and there were proteins in his urine.  The pediatrician advised us it’s best to go to the ER to have all other confirmation testing completed as test results would be much fast as they were have to send everything off to a lab and wait for it to come back.  We made arrangements for some friends of ours to watch the girls while we took my son to the nearby ER.
  This recent life change is the inspiration behind this calculator, it’s not super complex and full of complicated coding algorithms that would impress the best of the best, but what it is to me is important.  It’s something that gives me passage to practice my passion, while fulfilling my other passion, helping other people.  If this app just helps a single person to allow them to calculate how much insulin they, or a loved one needs, even if it’s out of shear convenience, as truth be told the math to figure it out isn’t super complicated either, then it is all worth it.
  * If you are using this app please keep in mind, I am not a medical professional, and assume no liability, this tool is intended for informational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment.  If you think you may have a medical emergency, immediately call 9-1-1.
    </h1>
  </div>
</template>
